#!/usr/bin/env bash
# Invoked on the Pi with one argument: absolute path to signalhub root (e.g. /home/kpi/ble/signalhub).
set -eu
trap 'rm -f /tmp/signalhub-remote-extract.sh' EXIT
REMOTE_SHUB="${1:?missing signalhub path}"
mkdir -p "$REMOTE_SHUB"
cd "$REMOTE_SHUB"
# If your PC clock is ahead of the Pi, GNU tar may warn about future timestamps; extract still succeeds.
tar -xzf /tmp/signalhub-deploy.tgz
rm -f /tmp/signalhub-deploy.tgz
find . -type f -name '*.sh' -exec sed -i 's/\r$//' {} + 2>/dev/null || true
chmod +x scripts/pi/*.sh 2>/dev/null || true

{
  echo "extract_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  grep -E '^version = ' pyproject.toml 2>/dev/null || echo "version = (missing pyproject.toml)"
  if grep -Fq "Generated by signalhub" src/signalhub/ble/reports.py 2>/dev/null; then
    echo "reports.py=includes_generator_blockquote"
  else
    echo "reports.py=OLD_STILL_NO_MATCH_DEPLOY_FROM_PC"
  fi
} > DEPLOY_STAMP.txt

bash scripts/pi/deploy_remote.sh
